version: '3.8'

services:
  db:
    image: postgres:13
    init: true
    container_name: chat_app_db
    working_dir: /home/mchliyah/Desktop/chat_app/data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - chat_app_network

  front-end:
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    init: true
    container_name: chat_app_front
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./front-end:/chat_app/front-end
    depends_on:
      - back-end
    networks:
      - chat_app_network

  back-end: 
    build: 
      context: .
      dockerfile: ./back-end/Dockerfile
    container_name: chat_app_back
    init: true
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./back-end:/chat_app/back-end
    depends_on:
      - db
    networks:
      - chat_app_network

networks:
  chat_app_network:
    driver: bridge
