version: '3.9'


services:
  db:
    image: postgres:14-alpine
    init: true
    ports:
      - '5432:5432'

    working_dir: /chat_app/back-end/data/db

    environment:
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - POSTGRES_DB=postgres
      - DB_HOST=db
      - DB_PORT=5432

    volumes:
      - ./data/db:/var/lib/postgresql/data/
    networks:
      - my_network

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile

    init: true
    ports:
      - '3000:3000'

    volumes:
      - ./front-end:/chat_app/front-end

    depends_on:
      - back-end
    networks:
      - my_network

  back-end: 
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    init: true
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./back-end:/chat_app/back-end

    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
