version: '3.9'


services:
  db:
    image: postgres:14-alpine
    init: true
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile

    init: true
    ports:
      - '3000:3000'

    volumes:
      - ./front-end:/app/front-end

    depends_on:
      - back-end

  back-end: 
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    init: true
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./back-end:/app/back-end

    depends_on:
      - db