# Generated by Django 5.0.2 on 2024-02-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=25),
        ),
    ]
