# Generated by Django 5.0.2 on 2024-02-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_delete_room_delete_usermessage_delete_userroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=30),
        ),
    ]
